[package]
name = "sha2_hashing"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
sha2 = "0.10.9"

[lib]
name = "lib"
path = "src/lib.rs"

[[bin]]
name = "bin"
path = "src/main.rs"

[profile.release]
opt-level = 0
# lto = true
debug=true
